<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>Robotopia.ModManager</AssemblyName>
    <RootNamespace>Robotopia.ModManager</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Robotopia.Mods.Abstractions\Robotopia.Mods.Abstractions.csproj" />
    <ProjectReference Include="..\Robotopia.ModManager.Core\Robotopia.ModManager.Core.csproj" />
    <ProjectReference Include="..\Robotopia.Mods.UnityUi\Robotopia.Mods.UnityUi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BepInEx" HintPath="$(BepInExCoreDir)\BepInEx.dll" Private="false" />
    <Reference Include="UnityEngine" HintPath="$(RobotopiaManagedDir)\UnityEngine.dll" Private="false" />
    <Reference Include="UnityEngine.CoreModule" HintPath="$(RobotopiaManagedDir)\UnityEngine.CoreModule.dll" Private="false" />
    <Reference Include="UnityEngine.InputLegacyModule" HintPath="$(RobotopiaManagedDir)\UnityEngine.InputLegacyModule.dll" Private="false" />
    <Reference Include="UnityEngine.TextRenderingModule" HintPath="$(RobotopiaManagedDir)\UnityEngine.TextRenderingModule.dll" Private="false" />
    <Reference Include="UnityEngine.UI" HintPath="$(RobotopiaManagedDir)\UnityEngine.UI.dll" Private="false" />
    <Reference Include="UnityEngine.UIModule" HintPath="$(RobotopiaManagedDir)\UnityEngine.UIModule.dll" Private="false" />
  </ItemGroup>
</Project>
