name: robotopia-launcher
version: 1.0.0
summary: QuantumWorks launcher for Robotopia
description: Desktop launcher and mod manager for Robotopia.

confinement: strict
base: core22
grade: stable

slots:
  dbus-quantumworks:
    interface: dbus
    bus: session
    name: com.quantumworks.robotopia.launcher

apps:
  robotopia_launcher_flutter:
    command: robotopia_launcher_flutter
    extensions: [gnome] # gnome includes the libraries required by flutter
    plugs:
    - network
    slots:
      - dbus-quantumworks
parts:
  robotopia_launcher_flutter:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
