#!/usr/bin/env python3
"""Keep the README diagrams, and the prose describing them, true to their source.

The four SVGs under assets/readme/ are generated by
assets/readme/source/build_readme_svg.py, but nothing ran the generator in CI,
so a hand-edited SVG or a composition change committed without regenerating
both themes went unnoticed. README.md then describes those pictures a third
time, in `alt` text written independently of the SVG's own `<desc>`, and a box
renamed in the diagram left both descriptions asserting a component that is no
longer drawn.

Three things are checked:

1.  Each committed SVG is byte-identical to what the generator produces, which
    makes the generator the only way to change a diagram.
2.  A light and dark pair share one `<title>` and `<desc>`. They come from one
    composition, so a divergence means one variant was edited by hand.
3.  Every component the diagram *draws* is named in the `alt` text README gives
    it, so a renamed box cannot leave the page describing the old one.

Deliberately not checked: that `alt` and `<desc>` are worded the same. They are
independent descriptions on purpose -- the `alt` text is the longer one, and
the `<desc>` describes the three assemblies by role rather than by name -- and
forcing them together would rewrite published accessibility text to satisfy a
gate rather than a reader.

Needs Pillow and the brand PNGs from Git LFS, the same as the generator:

    pip install Pillow
    git lfs pull
"""

from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path
from xml.etree import ElementTree

ROOT = Path(__file__).resolve().parents[2]
README = "README.md"
GENERATOR = "assets/readme/source/build_readme_svg.py"
SVG_NS = "{http://www.w3.org/2000/svg}"

# A label is a component name when it reads as an identifier rather than as
# prose: dotted PascalCase (`Mods.UnityUi`) or snake_case (`launcher_data`).
# Deriving the list this way rather than hard-coding it means a box added to
# the diagram is covered without anyone remembering to add it here.
COMPONENT = re.compile(
    r"[A-Za-z][A-Za-z0-9]*(?:\.[A-Z][A-Za-z0-9]*)+|[a-z][a-z0-9]*(?:_[a-z0-9]+)+"
)


class AuditToolError(RuntimeError):
    """A local prerequisite failed, so the audit could not be completed."""


def _read(relative: str) -> str:
    path = ROOT / relative
    if not path.is_file():
        raise AuditToolError(f"{relative} is missing; the diagrams cannot be checked.")
    return path.read_text(encoding="utf-8")


def readme_figures() -> list[dict[str, str]]:
    """The <picture> blocks README uses for the generated SVGs, light and dark."""
    readme = _read(README)
    figures = []
    for block in re.findall(r"<picture>(.*?)</picture>", readme, re.DOTALL):
        light = re.search(r'<img\s+src="\./(assets/readme/[\w-]+\.svg)"', block)
        if not light:
            continue  # Not one of the generated figures.
        dark = re.search(r'srcset="\./(assets/readme/[\w-]+\.svg)"', block)
        alt = re.search(r'alt="([^"]*)"', block)
        figures.append({
            "light": light.group(1),
            "dark": dark.group(1) if dark else "",
            "alt": alt.group(1) if alt else "",
        })
    if not figures:
        raise AuditToolError(
            f"Found no <picture> block in {README} pointing at assets/readme/*.svg. "
            "Did the markup change?"
        )
    return figures


def _parse(relative: str) -> ElementTree.Element:
    try:
        return ElementTree.fromstring(_read(relative))
    except ElementTree.ParseError as error:
        raise AuditToolError(f"{relative} is not well-formed XML: {error}") from error


def described(relative: str) -> tuple[str, str]:
    """The <title> and <desc> a screen reader announces for this SVG."""
    root = _parse(relative)
    title = root.find(f"{SVG_NS}title")
    desc = root.find(f"{SVG_NS}desc")
    if title is None or desc is None:
        raise AuditToolError(f"{relative} is missing its <title> or <desc>.")
    return (title.text or "").strip(), (desc.text or "").strip()


def drawn_components(relative: str) -> list[str]:
    """Identifier-shaped labels the SVG actually draws, in <text> elements.

    <title> and <desc> are not <text>, so this is what a sighted reader sees on
    the picture rather than what the file claims about itself.
    """
    root = _parse(relative)
    labels = " ".join(
        "".join(element.itertext()) for element in root.iter(f"{SVG_NS}text")
    )
    return sorted(set(COMPONENT.findall(labels)))


def regenerated() -> dict[str, bytes]:
    """What the generator produces right now, keyed by file name."""
    path = ROOT / GENERATOR
    if not path.is_file():
        raise AuditToolError(f"{GENERATOR} is missing.")
    spec = importlib.util.spec_from_file_location("build_readme_svg", path)
    if spec is None or spec.loader is None:
        raise AuditToolError(f"{GENERATOR} could not be loaded.")
    module = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(module)
    except ImportError as error:
        raise AuditToolError(
            f"{GENERATOR} could not be imported ({error}). It needs Pillow "
            "(`pip install Pillow`) and the brand PNGs from Git LFS "
            "(`git lfs pull`)."
        ) from error
    except OSError as error:
        raise AuditToolError(
            f"{GENERATOR} could not read a brand image ({error}). Run `git lfs pull`."
        ) from error

    built = {}
    for theme in module.THEMES:
        built[f"hero-{theme}.svg"] = module.build_hero(theme).encode("utf-8")
        built[f"architecture-{theme}.svg"] = module.build_architecture(theme).encode("utf-8")
    return built


def audit() -> list[str]:
    figures = readme_figures()
    failures: list[str] = []

    committed: set[str] = set()
    for figure in figures:
        light, dark, alt = figure["light"], figure["dark"], figure["alt"]
        committed.add(Path(light).name)

        if not dark:
            failures.append(
                f"{README}: {light} has no dark <source srcset>, so dark-mode readers "
                "get the light diagram."
            )
        if not alt.strip():
            failures.append(f"{README}: {light} is used with empty alt text.")

        for relative in (light, dark):
            if relative and not (ROOT / relative).is_file():
                failures.append(f"{README}: points at {relative}, which does not exist")

        if not (ROOT / light).is_file():
            continue
        if dark and (ROOT / dark).is_file():
            committed.add(Path(dark).name)
            if described(light) != described(dark):
                failures.append(
                    f"{light} and {dark} do not share one <title> and <desc>. They "
                    "come from one composition, so one of them was edited by hand."
                )

        missing = [c for c in drawn_components(light) if c not in alt]
        if missing:
            failures.append(
                f"{README}: the alt text for {light} does not name "
                f"{', '.join(missing)}, which the diagram draws"
            )

    for name, expected in regenerated().items():
        path = ROOT / "assets" / "readme" / name
        if not path.is_file():
            failures.append(f"assets/readme/{name}: the generator produces it, but it is missing")
        elif path.read_bytes() != expected:
            failures.append(
                f"assets/readme/{name}: does not match what {GENERATOR} produces. "
                "Regenerate it rather than editing the SVG."
            )
        elif name not in committed:
            # A generated diagram README never shows is a diagram nobody would
            # notice going wrong.
            failures.append(f"assets/readme/{name}: generated, but {README} never references it")

    return failures


def main() -> int:
    try:
        failures = audit()
    except AuditToolError as error:
        print(f"README diagram audit could not run: {error}", file=sys.stderr)
        return 2

    if failures:
        print("README diagram audit failed:", file=sys.stderr)
        for failure in failures:
            print(f"  - {failure}", file=sys.stderr)
        print(
            f"\nThe diagrams are generated by {GENERATOR}. Change the composition "
            "there, regenerate both themes, and update the alt text to match.",
            file=sys.stderr,
        )
        return 1

    print("README diagram audit passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
