part of '../models.dart';

const _knownManifestJsonKeys = <String>{
  r'$schema',
  'schemaVersion',
  'name',
  'displayName',
  'version',
  'author',
  'description',
  'entryAssembly',
  'entryType',
  'dependencies',
  'optionalDependencies',
  'conflicts',
  'loadAfter',
  'loadBefore',
  'supportedGameVersionRange',
  'supportedLoaderVersionRange',
  'supportedSdkVersionRange',
  'category',
  'tags',
  'icon',
  'screenshots',
  'homepage',
  'source',
  'license',
  'licenseFiles',
  'hashes',
  'capabilities',
  'platforms',
  'architectures',
  'contentTargets',
  'builtWith',
  'worldGamemodes',
  'apiAssemblies',
};

const _unsupportedManifestFields = <String>{
  'id',
  'title',
  'gameVersion',
  'gameVersionRange',
  'loaderVersionRange',
  'sdkVersionRange',
  'packageHashes',
  'gamemodes',
  'legacyFolders',
  'legacyFiles',
  'legacyPackages',
  'vpmDependencies',
  'permissions',
};

final _modIdPattern = RegExp(r'^[A-Za-z0-9][A-Za-z0-9_.-]{1,63}$');

const _knownCapabilities = {
  'asset-bundles',
  'filesystem',
  'filesystem-watch',
  'harmony-patch',
  'hud',
  'input',
  'navigation',
  'network',
  'microphone',
  'particles',
  'physics',
  'physics-settings',
  'player-control',
  'player-token',
  'prompt-overrides',
  'quality-settings',
  'remote-ai',
  'render-settings',
  'robot-spawning',
  'scene-management',
  'speech-to-text',
  'time',
  'ugc-livesync',
  'unsafe-native',
  'world-service',
};
