part of '../local_developer_repository.dart';

String _canonicalPathForRelativeReference(String input) {
  var current = p.normalize(p.absolute(input));
  final missingSegments = <String>[];
  while (FileSystemEntity.typeSync(current, followLinks: true) ==
      FileSystemEntityType.notFound) {
    final parent = p.dirname(current);
    if (parent == current) {
      return p.normalize(p.absolute(input));
    }
    missingSegments.insert(0, p.basename(current));
    current = parent;
  }

  try {
    final type = FileSystemEntity.typeSync(current, followLinks: true);
    final resolved = type == FileSystemEntityType.directory
        ? Directory(current).resolveSymbolicLinksSync()
        : File(current).resolveSymbolicLinksSync();
    return missingSegments.isEmpty
        ? resolved
        : p.joinAll([resolved, ...missingSegments]);
  } on FileSystemException {
    return p.normalize(p.absolute(input));
  }
}

String _canonicalRelativeReference(String target, {required String from}) =>
    p.relative(
      _canonicalPathForRelativeReference(target),
      from: _canonicalPathForRelativeReference(from),
    );

extension LocalDeveloperIoHelpers on LocalDeveloperRepository {
  Directory? _findProjectRoot(String startPath) {
    var current = FileSystemEntity.isDirectorySync(startPath)
        ? Directory(startPath).absolute
        : File(startPath).absolute.parent;
    while (true) {
      final projectFile = File(p.join(current.path, 'robotopia.project.json'));
      _recoverDeveloperAtomicBackupIfMissing(projectFile);
      if (projectFile.existsSync()) {
        return current;
      }
      final parent = current.parent;
      if (parent.path == current.path) {
        return null;
      }
      current = parent;
    }
  }

  Directory _requireProjectRoot(String projectPath) {
    final root = _findProjectRoot(projectPath);
    if (root == null) {
      throw StateError(
        'robotopia.project.json was not found from $projectPath',
      );
    }
    return root;
  }

  Future<DeveloperProject> _readProject(String root) async {
    final file = File(p.join(root, 'robotopia.project.json'));
    return DeveloperProject.fromJson(
      jsonDecode(
            utf8.decode(
              await _readDeveloperFileBounded(
                file,
                maxBytes: _maxDeveloperManifestBytes,
                label: 'robotopia.project.json',
              ),
            ),
          )
          as Map<String, Object?>,
    );
  }

  Future<void> _writeProject(String root, DeveloperProject project) async {
    _writeDeveloperTextAtomic(
      File(p.join(root, 'robotopia.project.json')),
      _prettyJson(project.toJson()),
    );
  }

  Future<DeveloperLock?> _readLock(String root) async {
    final file = File(p.join(root, 'robotopia.lock.json'));
    _recoverDeveloperAtomicBackupIfMissing(file);
    if (!file.existsSync()) {
      return null;
    }
    return DeveloperLock.fromJson(
      jsonDecode(
            utf8.decode(
              await _readDeveloperFileBounded(
                file,
                maxBytes: _maxDeveloperCatalogBytes,
                label: 'robotopia.lock.json',
              ),
            ),
          )
          as Map<String, Object?>,
    );
  }

  Future<void> _writeLock(String root, DeveloperLock lock) async {
    _writeDeveloperTextAtomic(
      File(p.join(root, 'robotopia.lock.json')),
      _prettyJson(lock.toJson()),
    );
  }

  // The built-in minimal starter (csproj + entry class; the manifest is generated by the template scaffolder).
  // Used as the fallback when templates/mod/ is absent (synthetic environments such as unit tests).
  Future<void> _writeStarterModSources(
    String root,
    String id,
    String name,
  ) async {
    final assembly = _assemblyName(id);
    final abstractionsProject = _canonicalRelativeReference(
      p.join(
        _repositoryRoot.path,
        'src',
        'Robotopia.Mods.Abstractions',
        'Robotopia.Mods.Abstractions.csproj',
      ),
      from: root,
    );
    await File(p.join(root, '$assembly.csproj')).writeAsString('''
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="robotopia.dev.props" Condition="Exists('robotopia.dev.props')" />
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>$assembly</AssemblyName>
    <RootNamespace>$assembly</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$abstractionsProject" Private="false" />
  </ItemGroup>
</Project>
''');
    await File(p.join(root, '${_typeName(id)}Mod.cs')).writeAsString('''
using Robotopia.Mods;

namespace $assembly
{
    public sealed class ${_typeName(id)}Mod : IRobotopiaMod
    {
        public void OnLoad(IModContext context)
        {
            context.Logger.Info("$name loaded.");
        }

        public void OnUnload()
        {
        }
    }
}
''');
  }

  Future<void> _writeUnityCompanionScaffold(String root, String name) async {
    final companion = Directory(p.join(root, 'unity-companion'));
    companion.createSync(recursive: true);

    // Copy the authored UGC companion Unity package from the repo template when available (the CLI runs from
    // the repo). In synthetic environments (e.g. unit tests) the template may be absent; the README + sample
    // config are still written so the scaffold is self-describing either way.
    if (_companionTemplateDir.existsSync()) {
      _copyDirectory(
        _companionTemplateDir,
        Directory(
          p.join(companion.path, 'Packages', 'com.robotopia.ugc-companion'),
        ),
      );
    }

    await File(p.join(companion.path, 'README.md')).writeAsString(
      '# $name Unity Companion\n\n'
      'Open this folder as a Unity project, or copy `Packages/com.robotopia.ugc-companion` into an existing '
      'Unity project. Use **Robotopia → UGC Live Sync** to author UGC content and live-sync it into the '
      'running game with no restart. See docs/UgcLiveSync.md for the full workflow.\n',
    );

    // A sample of the runtime config the game mod reads (config/robotopia.ugc.livesync.json). Copy it there and
    // set the watch folder to share content between the Unity companion and the game.
    _writeDeveloperTextAtomic(
      File(p.join(companion.path, 'robotopia.ugc.livesync.sample.json')),
      _prettyJson(const UgcLiveSyncSettings().toRuntimeConfig()),
    );
  }

  Future<void> _ensureProjectGitignore(String root) async {
    final file = File(p.join(root, '.gitignore'));
    final entries = [
      '.robotopia/packages/',
      '.robotopia/cache/',
      'robotopia.dev.props',
    ];
    final existing = file.existsSync()
        ? utf8.decode(
            await _readDeveloperFileBounded(
              file,
              maxBytes: _maxDeveloperManifestBytes,
              label: 'Project .gitignore',
            ),
          )
        : '';
    final buffer = StringBuffer(existing);
    if (existing.isNotEmpty && !existing.endsWith('\n')) {
      buffer.writeln();
    }
    for (final entry in entries) {
      if (!existing.split('\n').map((line) => line.trim()).contains(entry)) {
        buffer.writeln(entry);
      }
    }
    _writeDeveloperTextAtomic(file, buffer.toString());
  }

  Future<void> _writeDevProps(String root, DeveloperLock lock) async {
    final references = <String>[];
    for (final package in lock.packages) {
      for (final assembly in package.apiAssemblies) {
        final hintPath = p.join(
          root,
          '.robotopia',
          'packages',
          package.id,
          package.version,
          'extracted',
          assembly,
        );
        references.add('''
    <Reference Include="${p.basenameWithoutExtension(assembly)}">
      <HintPath>$hintPath</HintPath>
      <Private>false</Private>
    </Reference>''');
      }
    }
    _writeDeveloperTextAtomic(File(p.join(root, 'robotopia.dev.props')), '''
<Project>
  <ItemGroup>
${references.join('\n')}
  </ItemGroup>
</Project>
''');
  }

  Future<String> _which(String executable) async {
    final command = Platform.isWindows ? 'where' : 'which';
    final result = await runBoundedProcess(
      command,
      [executable],
      timeout: const Duration(seconds: 5),
      maxStdoutBytes: 1024 * 1024,
      maxStderrBytes: 64 * 1024,
    );
    if (result.exitCode != 0) {
      return '';
    }
    return result.stdout.toString().trim().split('\n').first.trim();
  }

  Future<String> _findUnityHub() async {
    final env = Platform.environment['UNITY_HUB_PATH'];
    if (env != null && env.isNotEmpty && File(env).existsSync()) {
      return env;
    }
    return _which(Platform.isWindows ? 'Unity Hub.exe' : 'unityhub');
  }

  Future<String> _findUnityEditor(DeveloperProject? project) async {
    final editors = await _scanUnityEditors();
    return RobotopiaUnityCompatibility.selectEditor(
          editors,
          configuredVersion: project?.unityCompanion.unityVersion ?? '',
        )?.path ??
        '';
  }

  // Locates the UGC Automerge sidecar script. Prefers the resolved repo root (correct when the launcher runs
  // from a packaged location), then walks up from the current directory for parity with the CLI.
  String? _findSidecar() {
    final fromRepo = p.join(
      _repositoryRoot.path,
      'tools',
      'ugc-automerge-sidecar',
      'index.mjs',
    );
    if (File(fromRepo).existsSync()) {
      return fromRepo;
    }

    var dir = Directory.current.absolute;
    while (true) {
      final candidate = File(
        p.join(dir.path, 'tools', 'ugc-automerge-sidecar', 'index.mjs'),
      );
      if (candidate.existsSync()) {
        return candidate.path;
      }
      final parent = dir.parent;
      if (parent.path == dir.path) {
        return null;
      }
      dir = parent;
    }
  }

  String _assemblyName(String id) => id
      .split(RegExp(r'[^A-Za-z0-9]+'))
      .where((part) => part.isNotEmpty)
      .map((part) => part[0].toUpperCase() + part.substring(1))
      .join();

  String _typeName(String id) {
    final name = _assemblyName(id);
    return name.isEmpty ? 'Robotopia' : name;
  }

  String _safeName(String raw) =>
      raw.replaceAll(RegExp(r'[^A-Za-z0-9_.-]+'), '_');

  String _prettyJson(Object? value) =>
      const JsonEncoder.withIndent('  ').convert(value);
}

String _findDeveloperRepoRoot(String? workingDirectory) {
  return _findQuantumWorksRoot(workingDirectory);
}

String _findQuantumWorksRoot(String? workingDirectory) {
  // Tests inject workingDirectory instead of mutating the process-global
  // Directory.current, which is shared across concurrent test isolates.
  final cwd = workingDirectory != null
      ? Directory(workingDirectory).absolute
      : Directory.current.absolute;
  for (final seed in _quantumWorksRootSeeds(cwd)) {
    final root = _walkUpForQuantumWorksRoot(seed);
    if (root != null) {
      return root.path;
    }
  }
  return cwd.path;
}

Iterable<Directory> _quantumWorksRootSeeds(Directory workingDirectory) sync* {
  final configured = Platform.environment['ROBOTOPIA_REPOSITORY_ROOT'];
  if (configured != null && configured.trim().isNotEmpty) {
    yield Directory(configured).absolute;
  }

  final executableDir = File(Platform.resolvedExecutable).absolute.parent;
  yield executableDir;

  final macResources = _macResourcesRoot(executableDir);
  if (macResources != null) {
    yield macResources;
  }

  yield workingDirectory;
}

Directory? _macResourcesRoot(Directory executableDir) {
  final contentsDir = executableDir.parent;
  if (p.basename(executableDir.path) != 'MacOS' ||
      p.basename(contentsDir.path) != 'Contents') {
    return null;
  }
  return Directory(
    p.join(contentsDir.path, 'Resources', 'QuantumWorks'),
  ).absolute;
}

Directory? _walkUpForQuantumWorksRoot(Directory seed) {
  var current = seed.absolute;
  while (true) {
    if (_isQuantumWorksRoot(current)) {
      return current;
    }
    final parent = current.parent;
    if (parent.path == current.path) {
      return null;
    }
    current = parent;
  }
}

bool _isQuantumWorksRoot(Directory directory) {
  if (File(p.join(directory.path, 'RobotopiaModManager.slnx')).existsSync()) {
    return true;
  }
  return Directory(p.join(directory.path, 'tools')).existsSync() &&
      Directory(p.join(directory.path, 'templates')).existsSync() &&
      Directory(p.join(directory.path, 'dist')).existsSync();
}
