part of '../local_developer_repository.dart';

extension LocalDeveloperIoHelpers on LocalDeveloperRepository {
  Directory? _findProjectRoot(String startPath) {
    var current = FileSystemEntity.isDirectorySync(startPath)
        ? Directory(startPath).absolute
        : File(startPath).absolute.parent;
    while (true) {
      final projectFile = File(p.join(current.path, 'topiaforge.project.json'));
      _recoverDeveloperAtomicBackupIfMissing(projectFile);
      if (projectFile.existsSync()) {
        return current;
      }
      final parent = current.parent;
      if (parent.path == current.path) {
        return null;
      }
      current = parent;
    }
  }

  Directory _requireProjectRoot(String projectPath) {
    final root = _findProjectRoot(projectPath);
    if (root == null) {
      throw StateError(
        'topiaforge.project.json was not found from $projectPath',
      );
    }
    return root;
  }

  Future<DeveloperProject> _readProject(String root) async {
    final file = File(p.join(root, 'topiaforge.project.json'));
    final decoded = jsonDecode(
      utf8.decode(
        await _readDeveloperFileBounded(
          file,
          maxBytes: _maxDeveloperManifestBytes,
          label: 'topiaforge.project.json',
        ),
      ),
    );
    if (decoded is! Map<String, Object?>) {
      throw const FormatException('topiaforge.project.json must be an object.');
    }
    if (decoded.containsKey('gameVersionRange') ||
        decoded.containsKey('loaderVersionRange')) {
      throw const FormatException(
        'Retired project version-range keys are not supported.',
      );
    }
    final project = DeveloperProject.fromJson(decoded);
    if (project.schemaVersion != 2) {
      throw const FormatException(
        'topiaforge.project.json must use schemaVersion 2.',
      );
    }
    return project;
  }

  Future<void> _writeProject(String root, DeveloperProject project) async {
    _writeDeveloperTextAtomic(
      File(p.join(root, 'topiaforge.project.json')),
      _prettyJson(project.toJson()),
    );
  }

  Future<DeveloperLock?> _readLock(String root) async {
    final file = File(p.join(root, 'topiaforge.lock.json'));
    _recoverDeveloperAtomicBackupIfMissing(file);
    if (!file.existsSync()) {
      return null;
    }
    final lock = DeveloperLock.fromJson(
      jsonDecode(
            utf8.decode(
              await _readDeveloperFileBounded(
                file,
                maxBytes: _maxDeveloperCatalogBytes,
                label: 'topiaforge.lock.json',
              ),
            ),
          )
          as Map<String, Object?>,
    );
    if (lock.schemaVersion != 2) {
      throw const FormatException(
        'topiaforge.lock.json must use schemaVersion 2.',
      );
    }
    return lock;
  }

  Future<void> _writeLock(String root, DeveloperLock lock) async {
    _writeDeveloperTextAtomic(
      File(p.join(root, 'topiaforge.lock.json')),
      _prettyJson(lock.toJson()),
    );
  }

  // The built-in minimal starter (csproj + entry class; the manifest is generated by the template scaffolder).
  // Used as the fallback when templates/mod/ is absent (synthetic environments such as unit tests).
  Future<void> _writeStarterModSources(
    String root,
    String id,
    String name,
  ) async {
    final assembly = _assemblyName(id);
    await File(p.join(root, '$assembly.csproj')).writeAsString('''
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="topiaforge.dev.props" Condition="Exists('topiaforge.dev.props')" />
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>$assembly</AssemblyName>
    <RootNamespace>$assembly</RootNamespace>
  </PropertyGroup>
  <Target Name="EnsureTopiaForgeSdk" BeforeTargets="ResolveAssemblyReferences"
          Condition="!Exists('topiaforge.dev.props')">
    <Error Text="TopiaForge SDK references are missing. Run 'topiaforge restore' in this project." />
  </Target>
</Project>
''');
    await File(p.join(root, '${_typeName(id)}Mod.cs')).writeAsString('''
using TopiaForge.Mods;

namespace $assembly
{
    public sealed class ${_typeName(id)}Mod : TopiaForgeMod
    {
        protected override void OnLoad()
        {
            Context.Logger.Info("$name loaded.");
        }

        protected override void OnUnload()
        {
        }
    }
}
''');
  }

  Future<void> _writeUnityCompanionScaffold(String root, String name) async {
    final companion = Directory(p.join(root, 'unity-companion'));
    companion.createSync(recursive: true);

    await File(p.join(companion.path, 'README.md')).writeAsString(
      '# $name Unity Companion\n\n'
      'Open this folder as a Unity project to author custom-world AssetBundles, '
      'then build them with `topiaforge world build`. Scene and robot authoring '
      'lives in the official Robotopia Creator at https://robotopia.gg/editor/.\n',
    );
  }

  Future<void> _ensureProjectGitignore(String root) async {
    final file = File(p.join(root, '.gitignore'));
    final entries = [
      '.topiaforge/packages/',
      '.topiaforge/cache/',
      'topiaforge.dev.props',
    ];
    final existing = file.existsSync()
        ? utf8.decode(
            await _readDeveloperFileBounded(
              file,
              maxBytes: _maxDeveloperManifestBytes,
              label: 'Project .gitignore',
            ),
          )
        : '';
    final buffer = StringBuffer(existing);
    if (existing.isNotEmpty && !existing.endsWith('\n')) {
      buffer.writeln();
    }
    for (final entry in entries) {
      if (!existing.split('\n').map((line) => line.trim()).contains(entry)) {
        buffer.writeln(entry);
      }
    }
    _writeDeveloperTextAtomic(file, buffer.toString());
  }

  Future<void> _writeDevProps(
    String root,
    DeveloperLock? lock, {
    SdkReferencePack? sdk,
  }) async {
    final references = <String>[];
    for (final package in lock?.packages ?? const <LockedPackage>[]) {
      for (final assembly in package.apiAssemblies) {
        final hintPath = p.join(
          root,
          '.topiaforge',
          'packages',
          package.id,
          package.version,
          'extracted',
          assembly,
        );
        references.add('''
    <Reference Include="${_xmlMsBuildValue(p.basenameWithoutExtension(assembly))}">
      <HintPath>${_xmlMsBuildValue(hintPath)}</HintPath>
      <Private>false</Private>
    </Reference>''');
      }
    }
    final sdkVersion = sdk?.version ?? '';
    final sdkFeed = sdk == null ? '' : _xmlMsBuildValue(sdk.feed.path);
    final nugetCache = sdk == null
        ? ''
        : _xmlMsBuildValue(
            p.join(
              _dataRoot.path,
              'sdk-nuget-cache',
              sdk.version,
              _compactSha256(sdk.manifestSha256),
            ),
          );
    final managedDir = _resolveRobotopiaManagedDir();
    final managedProperty = managedDir.isEmpty
        ? ''
        : '    <RobotopiaManagedDir Condition="\'\$(RobotopiaManagedDir)\' == \'\'">${_xmlMsBuildValue(managedDir)}</RobotopiaManagedDir>';
    _writeDeveloperTextAtomic(File(p.join(root, 'topiaforge.dev.props')), '''
<Project>
  <PropertyGroup>
    <TopiaForgeSdkVersion>$sdkVersion</TopiaForgeSdkVersion>
    <TopiaForgeSdkFeed>$sdkFeed</TopiaForgeSdkFeed>
    <TopiaForgeNuGetCache>$nugetCache</TopiaForgeNuGetCache>
    <RestoreAdditionalProjectSources>\$(RestoreAdditionalProjectSources);\$(TopiaForgeSdkFeed)</RestoreAdditionalProjectSources>
    <RestorePackagesPath>\$(TopiaForgeNuGetCache)</RestorePackagesPath>
$managedProperty
  </PropertyGroup>
  <ItemGroup>
${references.join('\n')}
  </ItemGroup>
</Project>
''');
  }

  String _compactSha256(String hex) {
    final bytes = <int>[
      for (var offset = 0; offset < hex.length; offset += 2)
        int.parse(hex.substring(offset, offset + 2), radix: 16),
    ];
    return base64Url.encode(bytes).replaceAll('=', '');
  }

  String _resolveRobotopiaManagedDir() {
    for (final key in const ['RobotopiaManagedDir', 'ROBOTOPIA_MANAGED_DIR']) {
      final value = Platform.environment[key]?.trim() ?? '';
      if (value.isNotEmpty && Directory(value).existsSync()) {
        return Directory(value).absolute.path;
      }
    }

    String fromGameRoot(String gameRoot) {
      final root = Directory(gameRoot).absolute.path;
      final mac = p.join(root, 'Contents', 'Resources', 'Data', 'Managed');
      if (Directory(mac).existsSync()) return mac;
      final windows = p.join(root, 'Robotopia_Data', 'Managed');
      return Directory(windows).existsSync() ? windows : '';
    }

    final environmentGame =
        Platform.environment['ROBOTOPIA_GAME_DIR']?.trim() ?? '';
    if (environmentGame.isNotEmpty) {
      final managed = fromGameRoot(environmentGame);
      if (managed.isNotEmpty) return managed;
    }

    final settings = File(p.join(_dataRoot.path, 'settings.json'));
    if (settings.existsSync()) {
      try {
        final decoded = jsonDecode(
          utf8.decode(
            _readDeveloperFileBoundedSync(
              settings,
              maxBytes: _maxDeveloperManifestBytes,
              label: 'TopiaForge settings',
            ),
          ),
        );
        final gamePath = decoded is Map ? decoded['gamePath'] : null;
        if (gamePath is String && gamePath.trim().isNotEmpty) {
          final managed = fromGameRoot(gamePath);
          if (managed.isNotEmpty) return managed;
        }
      } on Object {
        // An invalid launcher settings file must not break safe SDK restore.
      }
    }

    final localProps = File(
      p.join(_repositoryRoot.path, 'Directory.Build.local.props'),
    );
    if (localProps.existsSync()) {
      try {
        final text = utf8.decode(
          _readDeveloperFileBoundedSync(
            localProps,
            maxBytes: _maxDeveloperManifestBytes,
            label: 'Directory.Build.local.props',
          ),
        );
        final match = RegExp(
          r'<RobotopiaManagedDir>\s*([^<]+?)\s*</RobotopiaManagedDir>',
        ).firstMatch(text);
        if (match != null && Directory(match.group(1)!).existsSync()) {
          return Directory(match.group(1)!).absolute.path;
        }
      } on Object {
        // Source checkouts without local configuration remain safe-only.
      }
    }
    return '';
  }

  Future<String> _which(String executable) async {
    final command = Platform.isWindows ? 'where' : 'which';
    final result = await runBoundedProcess(
      command,
      [executable],
      timeout: const Duration(seconds: 5),
      maxStdoutBytes: 1024 * 1024,
      maxStderrBytes: 64 * 1024,
    );
    if (result.exitCode != 0) {
      return '';
    }
    return result.stdout.toString().trim().split('\n').first.trim();
  }

  Future<String> _findUnityHub() async {
    final env = Platform.environment['UNITY_HUB_PATH'];
    if (env != null && env.isNotEmpty && File(env).existsSync()) {
      return env;
    }
    return _which(Platform.isWindows ? 'Unity Hub.exe' : 'unityhub');
  }

  Future<String> _findUnityEditor(DeveloperProject? project) async {
    final editors = await _scanUnityEditors();
    return RobotopiaGameUnityCompatibility.selectEditor(
          editors,
          configuredVersion: project?.unityCompanion.unityVersion ?? '',
        )?.path ??
        '';
  }


  String _assemblyName(String id) => id
      .split(RegExp(r'[^A-Za-z0-9]+'))
      .where((part) => part.isNotEmpty)
      .map((part) => part[0].toUpperCase() + part.substring(1))
      .join();

  String _typeName(String id) {
    final name = _assemblyName(id);
    return name.isEmpty ? 'TopiaForge' : name;
  }

  String _safeName(String raw) =>
      raw.replaceAll(RegExp(r'[^A-Za-z0-9_.-]+'), '_');

  String _prettyJson(Object? value) =>
      const JsonEncoder.withIndent('  ').convert(value);
}

String _xmlMsBuildValue(String input) => input
    .replaceAll('&', '&amp;')
    .replaceAll('"', '&quot;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;');

String _findDeveloperRepoRoot(String? workingDirectory) {
  return _findTopiaForgeRoot(workingDirectory);
}

String _findTopiaForgeRoot(String? workingDirectory) {
  // Tests inject workingDirectory instead of mutating the process-global
  // Directory.current, which is shared across concurrent test isolates.
  final cwd = workingDirectory != null
      ? Directory(workingDirectory).absolute
      : Directory.current.absolute;
  for (final seed in _topiaForgeRootSeeds(cwd)) {
    final root = _walkUpForTopiaForgeRoot(seed);
    if (root != null) {
      return root.path;
    }
  }
  return cwd.path;
}

Iterable<Directory> _topiaForgeRootSeeds(Directory workingDirectory) sync* {
  final configured = Platform.environment['TOPIAFORGE_REPOSITORY_ROOT'];
  if (configured != null && configured.trim().isNotEmpty) {
    yield Directory(configured).absolute;
  }

  final executableDir = File(Platform.resolvedExecutable).absolute.parent;
  yield executableDir;

  final macResources = _macResourcesRoot(executableDir);
  if (macResources != null) {
    yield macResources;
  }

  yield workingDirectory;
}

Directory? _macResourcesRoot(Directory executableDir) {
  final contentsDir = executableDir.parent;
  if (p.basename(executableDir.path) != 'MacOS' ||
      p.basename(contentsDir.path) != 'Contents') {
    return null;
  }
  return Directory(
    p.join(contentsDir.path, 'Resources', 'TopiaForge'),
  ).absolute;
}

Directory? _walkUpForTopiaForgeRoot(Directory seed) {
  var current = seed.absolute;
  while (true) {
    if (_isTopiaForgeRoot(current)) {
      return current;
    }
    final parent = current.parent;
    if (parent.path == current.path) {
      return null;
    }
    current = parent;
  }
}

bool _isTopiaForgeRoot(Directory directory) {
  if (File(p.join(directory.path, 'TopiaForge.slnx')).existsSync()) {
    return true;
  }
  return Directory(p.join(directory.path, 'tools')).existsSync() &&
      Directory(p.join(directory.path, 'templates')).existsSync() &&
      Directory(p.join(directory.path, 'dist')).existsSync();
}
