<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>Robotopia.NoFeedbackUrl</AssemblyName>
    <RootNamespace>Robotopia.NoFeedbackUrl</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Robotopia.Mods.Abstractions\Robotopia.Mods.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony" HintPath="$(BepInExCoreDir)\0Harmony.dll" Private="false" />
    <Reference Include="GameCode" HintPath="$(RobotopiaManagedDir)\GameCode.dll" Private="false" />
  </ItemGroup>
</Project>
