<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="topiaforge.dev.props" Condition="Exists('topiaforge.dev.props')" />
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>{{ASSEMBLY_NAME}}</AssemblyName>
    <RootNamespace>{{ASSEMBLY_NAME}}</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="{{ABSTRACTIONS_PROJECT}}" Private="false" />
    <ProjectReference Include="{{UNITYUI_PROJECT}}" Private="false" />
  </ItemGroup>
</Project>
